DROP TABLE IF EXISTS niveaux; 
DROP TABLE IF EXISTS salle; 
DROP TABLE IF EXISTS eleve; 
DROP TABLE IF EXISTS cours; 

CREATE TABLE niveaux (
    ID VARCHAR  PRIMARY KEY NOT NULL,
    LIBELLE VARCHAR NOT NULL
    );

CREATE TABLE salle (
    NOM VARCHAR PRIMARY KEY NOT NULL,
    CAPACITE INT NOT NULL
    );

CREATE TABLE eleve (
    ID INT PRIMARY KEY NOT NULL, 
    NOM VARCHAR NOT NULL, 
    PRENOM VARCHAR NOT NULL, 
    AGE INT NOT NULL, 
    NIVEAU_SCOLAIRE VARCHAR REFERENCES niveaux (ID)
    );

CREATE TABLE cours (
    ID VARCHAR PRIMARY KEY NOT NULL, 
    DEBUT DATETIME NOT NULL, 
    FIN DATETIME NOT NULL, 
    NIVEAU_SCOLAIRE VARCHAR REFERENCES niveaux (ID), 
    SALLE VARCHAR REFERENCES salle (NOM)
    );